name: eeg_bids_collector_app
description: "A Flutter application for collecting EEG data in BIDS format."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 状態管理
  provider: ^6.1.2

  # BLE & Permissions
  permission_handler: ^11.3.1
  flutter_blue_plus: ^1.32.4

  # データ処理 & 通信
  zstandard: ^1.3.27
  http: ^1.2.1
  url_launcher: ^6.1.14
  file_picker: ^8.0.5
  path: ^1.9.0
  record: ^6.0.0

  # メディア (カメラ & マイク)
  camera: ^0.11.0+1

  # UI
  fl_chart: ^0.68.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
